// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0HlooLpPJeB8MQRru4T3hnSPKvQ_b5Yg',
    appId: '1:675064809117:android:46993c2d1cf83fe052f674',
    messagingSenderId: '675064809117',
    projectId: 'philgo-64b1a',
    databaseURL: 'https://philgo-64b1a.firebaseio.com',
    storageBucket: 'philgo-64b1a.firebasestorage.app',
    measurementId: 'G-2NSLM1JWQL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm76FlLe1YLacXe-RqdJdlGB1F7lXKt_E',
    appId: '1:675064809117:ios:7fa44aab3006c1d252f674',
    messagingSenderId: '675064809117',
    projectId: 'philgo-64b1a',
    databaseURL: 'https://philgo-64b1a.firebaseio.com',
    storageBucket: 'philgo-64b1a.firebasestorage.app',
    androidClientId: '675064809117-7t1bv88t7h9qjkt6tft9aqt392sq6d54.apps.googleusercontent.com',
    iosClientId: '675064809117-1413b6s69jp8l9bc68ksjs8q1a9bu79f.apps.googleusercontent.com',
    iosBundleId: 'com.philgo.philgo',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Ee4S1Hd71I9NuO1-Y80zhsBOPaCJj9U',
    appId: '1:675064809117:web:f77f8569bc608a5c52f674',
    messagingSenderId: '675064809117',
    projectId: 'philgo-64b1a',
    authDomain: 'philgo-64b1a.firebaseapp.com',
    databaseURL: 'https://philgo-64b1a.firebaseio.com',
    storageBucket: 'philgo-64b1a.firebasestorage.app',
    measurementId: 'G-2NSLM1JWQL',
  );

}