name: philgo
description: "A new Flutter project."

publish_to: "none"

version: 2.0.13+43

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.3.0
  easy_phone_sign_in:
    path: packages/easy_phone_sign_in
  file_cache_flutter: ^0.0.1
  file_picker: ^10.3.3
  firebase_analytics: ^11.6.0
  firebase_auth: ^5.6.1
  firebase_core: ^3.15.1
  firebase_crashlytics: ^4.3.10
  firebase_database: ^11.3.10
  firebase_messaging: ^15.2.8
  firebase_remote_config: ^5.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  flutter_staggered_grid_view: ^0.7.0
  font_awesome_flutter: ^10.12.0
  go_router: ^16.0.0
  google_fonts: ^6.2.1
  http: ^1.6.0
  image_picker: ^1.2.0
  infinite_scroll_pagination: ^5.1.1
  intl: any
  omni_video_player: ^4.0.0-beta
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  philgo_api:
    path: packages/philgo_api
  provider: ^6.1.5+1
  receive_sharing_intent: ^1.8.1
  shorebird_code_push: ^2.0.5
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

dependency_overrides:
  file_cache_flutter:
    path: packages/file_cache_flutter
  font_awesome_flutter:
    path: packages/font_awesome_flutter

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/img/logo/philgo_v6_app_logo.png
    - assets/img/logo/philgo_wide_logo_icon.png
    - assets/img/logo/philgo_wide_logo.png
    - shorebird.yaml

# 명령어: dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: tmp/philgo_app_splash.png
  # branding: assets/branding-production.png
  # color_dark: "#121212"
  # image_dark: assets/logo-production.png
  # branding_dark: assets/branding-production.png

  android_12:
    image: tmp/philgo_app_splash.png
    icon_background_color: "#ffffff"
    # image_dark: assets/logo-production.png
    # icon_background_color_dark: "#121212"

  web: false

# 명령어: dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "tmp/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
