final List<String> locations = [
  "Bangued (Abra)",
  "Boliney (Abra)",
  "Bucay (Abra)",
  "Bucloc (Abra)",
  "Daguioman (Abra)",
  "Danglas (Abra)",
  "Dolores (Abra)",
  "La Paz (Abra)",
  "Lacub (Abra)",
  "Lagangilang (Abra)",
  "Lagayan (Abra)",
  "Langiden (Abra)",
  "Licuan-Baay (Abra)",
  "Luba (Abra)",
  "Malibcong (Abra)",
  "Manabo (Abra)",
  "Pe├â┬▒arrubia (Abra)",
  "Pidigan (Abra)",
  "Pilar (Abra)",
  "Sallapadan (Abra)",
  "San Isidro (Abra)",
  "San Juan (Abra)",
  "San Quintin (Abra)",
  "Tayum (Abra)",
  "Tineg (Abra)",
  "Tubo (Abra)",
  "Villaviciosa (Abra)",
  "Bacacay (Albay)",
  "Camalig (Albay)",
  "Daraga (Albay)",
  "Guinobatan (Albay)",
  "Jovellar (Albay)",
  "Legazpi City (Albay) - 레가스피",
  "Libon (Albay)",
  "Ligao City (Albay)",
  "Malilipot (Albay)",
  "Malinao (Albay)",
  "Manito (Albay)",
  "Oas (Albay)",
  "Pio Duran (Albay)",
  "Polangui (Albay)",
  "Rapu-Rapu (Albay)",
  "Santo Domingo (Albay)",
  "Tabaco City (Albay)",
  "Tiwi (Albay)",
  "Calanasan (Apayao)",
  "Conner (Apayao)",
  "Flora (Apayao)",
  "Kabugao (Apayao)",
  "Luna (Apayao)",
  "Pudtol (Apayao)",
  "Santa Marcela (Apayao)",
  "Baler (Aurora)",
  "Casiguran (Aurora)",
  "Dilasag (Aurora)",
  "Dinalungan (Aurora)",
  "Dingalan (Aurora)",
  "Dipaculao (Aurora)",
  "Maria Aurora (Aurora)",
  "San Luis (Aurora)",
  "Abucay (Bataan)",
  "Bagac (Bataan)",
  "Balanga City (Bataan)",
  "Dinalupihan (Bataan)",
  "Hermosa (Bataan)",
  "Limay (Bataan)",
  "Mariveles (Bataan)",
  "Morong (Bataan)",
  "Orani (Bataan)",
  "Orion (Bataan)",
  "Pilar (Bataan)",
  "Samal (Bataan)",
  "Basco (Batanes)",
  "Itbayat (Batanes)",
  "Ivana (Batanes)",
  "Mahatao (Batanes)",
  "Sabtang (Batanes)",
  "Uyugan (Batanes)",
  "Agoncillo (Batangas)",
  "Alitagtag (Batangas)",
  "Balayan (Batangas)",
  "Balete (Batangas)",
  "Batangas City (Batangas) - 바탕가스",
  "Bauan (Batangas)",
  "Calaca (Batangas)",
  "Calatagan (Batangas)",
  "Cuenca (Batangas)",
  "Ibaan (Batangas)",
  "Laurel (Batangas)",
  "Lemery (Batangas)",
  "Lian (Batangas)",
  "Lipa City (Batangas)",
  "Lobo (Batangas)",
  "Mabini (Batangas)",
  "Malvar (Batangas)",
  "Mataas Na Kahoy (Batangas)",
  "Nasugbu (Batangas)",
  "Padre Garcia (Batangas)",
  "Rosario (Batangas)",
  "San Jose (Batangas)",
  "San Juan (Batangas)",
  "San Luis (Batangas)",
  "San Nicolas (Batangas)",
  "San Pascual (Batangas)",
  "Santa Teresita (Batangas)",
  "Santo Tomas (Batangas)",
  "Taal (Batangas) - 따알",
  "Talisay (Batangas)",
  "Tanauan City (Batangas)",
  "Taysan (Batangas)",
  "Tingloy (Batangas)",
  "Tuy (Batangas)",
  "Atok (Benguet)",
  "Baguio City (Benguet) - 바기오",
  "Bakun (Benguet)",
  "Bokod (Benguet)",
  "Buguias (Benguet)",
  "Itogon (Benguet)",
  "Kabayan (Benguet)",
  "Kapangan (Benguet)",
  "Kibungan (Benguet)",
  "La Trinidad (Benguet)",
  "Mankayan (Benguet)",
  "Sablan (Benguet)",
  "Tuba (Benguet)",
  "Tublay (Benguet)",
  "Angat (Bulacan)",
  "Balagtas (Bulacan)",
  "Baliuag (Bulacan)",
  "Bocaue (Bulacan)",
  "Bulacan (Bulacan) - 불라칸",
  "Bustos (Bulacan)",
  "Calumpit (Bulacan)",
  "Do├â┬▒a Remedios Trinidad (Bulacan)",
  "Guiguinto (Bulacan)",
  "Hagonoy (Bulacan)",
  "Malolos City (Bulacan)",
  "Marilao (Bulacan)",
  "Meycauayan City (Bulacan)",
  "Norzagaray (Bulacan)",
  "Obando (Bulacan)",
  "Pandi (Bulacan)",
  "Paombong (Bulacan)",
  "Plaridel (Bulacan)",
  "Pulilan (Bulacan)",
  "San Ildefonso (Bulacan)",
  "San Jose del Monte City (Bulacan)",
  "San Miguel (Bulacan)",
  "San Rafael (Bulacan)",
  "Santa Maria (Bulacan)",
  "Abulug (Cagayan)",
  "Alcala (Cagayan)",
  "Allacapan (Cagayan)",
  "Amulung (Cagayan)",
  "Aparri (Cagayan)",
  "Baggao (Cagayan)",
  "Ballesteros (Cagayan)",
  "Buguey (Cagayan)",
  "Calayan (Cagayan)",
  "Camalaniugan (Cagayan)",
  "Claveria (Cagayan)",
  "Enrile (Cagayan)",
  "Gattaran (Cagayan)",
  "Gonzaga (Cagayan)",
  "Iguig (Cagayan)",
  "Lal-Lo (Cagayan)",
  "Lasam (Cagayan)",
  "Pamplona (Cagayan)",
  "Pe├â┬▒ablanca (Cagayan)",
  "Piat (Cagayan)",
  "Rizal (Cagayan)",
  "Sanchez-Mira (Cagayan)",
  "Santa Ana (Cagayan)",
  "Santa Praxedes (Cagayan)",
  "Santa Teresita (Cagayan)",
  "Santo Ni├â┬▒o (Cagayan)",
  "Solana (Cagayan)",
  "Tuao (Cagayan)",
  "Tuguegarao City (Cagayan)",
  "Basud (Camarines Norte)",
  "Capalonga (Camarines Norte)",
  "Daet (Camarines Norte)",
  "Jose Panganiban (Camarines Norte)",
  "Labo (Camarines Norte)",
  "Mercedes (Camarines Norte)",
  "Paracale (Camarines Norte)",
  "San Lorenzo Ruiz (Camarines Norte)",
  "San Vicente (Camarines Norte)",
  "Santa Elena (Camarines Norte)",
  "Talisay (Camarines Norte)",
  "Vinzons (Camarines Norte)",
  "Baao (Camarines Sur)",
  "Balatan (Camarines Sur)",
  "Bato (Camarines Sur)",
  "Bombon (Camarines Sur)",
  "Buhi (Camarines Sur)",
  "Bula (Camarines Sur)",
  "Cabusao (Camarines Sur)",
  "Calabanga (Camarines Sur)",
  "Canaman (Camarines Sur)",
  "Caramoan (Camarines Sur)",
  "Del Gallego (Camarines Sur)",
  "Gainza (Camarines Sur)",
  "Garchitorena (Camarines Sur)",
  "Goa (Camarines Sur)",
  "Iriga City (Camarines Sur)",
  "Lagonoy (Camarines Sur)",
  "Libmanan (Camarines Sur)",
  "Lupi (Camarines Sur)",
  "Magarao (Camarines Sur)",
  "Milaor (Camarines Sur)",
  "Minalabac (Camarines Sur)",
  "Nabua (Camarines Sur)",
  "Naga City (Camarines Sur)",
  "Ocampo (Camarines Sur)",
  "Pamplona (Camarines Sur)",
  "Pasacao (Camarines Sur)",
  "Pili (Camarines Sur)",
  "Presentacion (Camarines Sur)",
  "Ragay (Camarines Sur)",
  "Sagnay (Camarines Sur)",
  "San Fernando (Camarines Sur)",
  "San Jose (Camarines Sur)",
  "Sipocot (Camarines Sur)",
  "Siruma (Camarines Sur)",
  "Tigaon (Camarines Sur)",
  "Tinambac (Camarines Sur)",
  "Bagamanoc (Catanduanes)",
  "Baras (Catanduanes)",
  "Bato (Catanduanes)",
  "Caramoran (Catanduanes)",
  "Gigmoto (Catanduanes)",
  "Pandan (Catanduanes)",
  "Panganiban (Catanduanes)",
  "San Andres (Catanduanes)",
  "San Miguel (Catanduanes)",
  "Viga (Catanduanes)",
  "Virac (Catanduanes)",
  "Alfonso (Cavite)",
  "Amadeo (Cavite)",
  "Bacoor (Cavite) - 바쿠어",
  "Carmona (Cavite)",
  "Dasmari├â┬▒as (Cavite)",
  "General Emilio Aguinaldo (Cavite)",
  "General Mariano Alvarez (Cavite)",
  "General Trias (Cavite)",
  "Imus (Cavite) - 이무스",
  "Indang (Cavite)",
  "Kawit (Cavite)",
  "Magallanes (Cavite)",
  "Maragondon (Cavite)",
  "Mendez (Cavite)",
  "Naic (Cavite)",
  "Rosario (Cavite)",
  "Silang (Cavite) - 실랑",
  "Tagaytay City (Cavite) - 타가이타이",
  "Tanza (Cavite)",
  "Ternate (Cavite)",
  "Trece Martires City (Cavite)",
  "Aguinaldo (Ifugao)",
  "Alfonso Lista (Ifugao)",
  "Asipulo (Ifugao)",
  "Banaue (Ifugao)",
  "Hingyon (Ifugao)",
  "Hungduan (Ifugao)",
  "Kiangan (Ifugao)",
  "Lagawe (Ifugao)",
  "Lamut (Ifugao)",
  "Mayoyao (Ifugao)",
  "Tinoc (Ifugao)",
  "Adams (Ilocos Norte)",
  "Bacarra (Ilocos Norte)",
  "Badoc (Ilocos Norte)",
  "Bangui (Ilocos Norte)",
  "Banna (Ilocos Norte)",
  "Batac City (Ilocos Norte)",
  "Burgos (Ilocos Norte)",
  "Carasi (Ilocos Norte)",
  "Currimao (Ilocos Norte)",
  "Dingras (Ilocos Norte)",
  "Dumalneg (Ilocos Norte)",
  "Laoag City (Ilocos Norte)",
  "Marcos (Ilocos Norte)",
  "Nueva Era (Ilocos Norte)",
  "Pagudpud (Ilocos Norte)",
  "Paoay (Ilocos Norte)",
  "Pasuquin (Ilocos Norte)",
  "Piddig (Ilocos Norte)",
  "Pinili (Ilocos Norte)",
  "San Nicolas (Ilocos Norte)",
  "Sarrat (Ilocos Norte)",
  "Solsona (Ilocos Norte)",
  "Vintar (Ilocos Norte)",
  "Alilem (Ilocos Sur)",
  "Banayoyo (Ilocos Sur)",
  "Bantay (Ilocos Sur)",
  "Burgos (Ilocos Sur)",
  "Cabugao (Ilocos Sur)",
  "Candon City (Ilocos Sur)",
  "Caoayan (Ilocos Sur)",
  "Cervantes (Ilocos Sur)",
  "Galimuyod (Ilocos Sur)",
  "Gregorio Del Pilar (Ilocos Sur)",
  "Lidlidda (Ilocos Sur)",
  "Magsingal (Ilocos Sur)",
  "Nagbukel (Ilocos Sur)",
  "Narvacan (Ilocos Sur)",
  "Quirino (Ilocos Sur)",
  "Salcedo (Ilocos Sur)",
  "San Emilio (Ilocos Sur)",
  "San Esteban (Ilocos Sur)",
  "San Ildefonso (Ilocos Sur)",
  "San Juan (Ilocos Sur)",
  "San Vicente (Ilocos Sur)",
  "Santa (Ilocos Sur)",
  "Santa Catalina (Ilocos Sur)",
  "Santa Cruz (Ilocos Sur)",
  "Santa Lucia (Ilocos Sur)",
  "Santa Maria (Ilocos Sur)",
  "Santiago (Ilocos Sur)",
  "Santo Domingo (Ilocos Sur)",
  "Sigay (Ilocos Sur)",
  "Sinait (Ilocos Sur)",
  "Sugpon (Ilocos Sur)",
  "Suyo (Ilocos Sur)",
  "Tagudin (Ilocos Sur)",
  "Vigan City (Ilocos Sur)",
  "Alicia (Isabela)",
  "Angadanan (Isabela)",
  "Aurora (Isabela)",
  "Benito Soliven (Isabela)",
  "Burgos (Isabela)",
  "Cabagan (Isabela)",
  "Cabatuan (Isabela)",
  "Cauayan City (Isabela)",
  "Cordon (Isabela)",
  "Delfin Albano (Isabela)",
  "Dinapigue (Isabela)",
  "Divilacan (Isabela)",
  "Echague (Isabela)",
  "Gamu (Isabela)",
  "Ilagan (Isabela)",
  "Jones (Isabela)",
  "Luna (Isabela)",
  "Maconacon (Isabela)",
  "Mallig (Isabela)",
  "Naguilian (Isabela)",
  "Palanan (Isabela)",
  "Quezon (Isabela)",
  "Quirino (Isabela)",
  "Ramon (Isabela)",
  "Reina Mercedes (Isabela)",
  "Roxas (Isabela)",
  "San Agustin (Isabela)",
  "San Guillermo (Isabela)",
  "San Isidro (Isabela)",
  "San Manuel (Isabela)",
  "San Mariano (Isabela)",
  "San Mateo (Isabela)",
  "San Pablo (Isabela)",
  "Santa Maria (Isabela)",
  "Santiago City (Isabela)",
  "Santo Tomas (Isabela)",
  "Tumauini (Isabela)",
  "Balbalan (Kalinga)",
  "Lubuagan (Kalinga)",
  "Pasil (Kalinga)",
  "Pinukpuk (Kalinga)",
  "Rizal (Kalinga)",
  "Tabuk City (Kalinga)",
  "Tanudan (Kalinga)",
  "Tinglayan (Kalinga)",
  "Agoo (La Union)",
  "Aringay (La Union)",
  "Bacnotan (La Union)",
  "Bagulin (La Union)",
  "Balaoan (La Union)",
  "Bangar (La Union)",
  "Bauang (La Union)",
  "Burgos (La Union)",
  "Caba (La Union)",
  "Luna (La Union)",
  "Naguilian (La Union)",
  "Pugo (La Union)",
  "Rosario (La Union)",
  "San Fernando City (La Union)",
  "San Gabriel (La Union)",
  "San Juan (La Union)",
  "Santo Tomas (La Union)",
  "Santol (La Union)",
  "Sudipen (La Union)",
  "Tubao (La Union)",
  "Alaminos (Laguna)",
  "Bay (Laguna)",
  "Bi├â┬▒an (Laguna)",
  "Cabuyao (Laguna)",
  "Calamba City (Laguna)",
  "Calauan (Laguna)",
  "Cavinti (Laguna)",
  "Famy (Laguna)",
  "Kalayaan (Laguna)",
  "Liliw (Laguna)",
  "Los Ba├â┬▒os (Laguna)",
  "Luisiana (Laguna)",
  "Lumban (Laguna)",
  "Mabitac (Laguna)",
  "Magdalena (Laguna)",
  "Majayjay (Laguna)",
  "Nagcarlan (Laguna)",
  "Paete (Laguna)",
  "Pagsanjan (Laguna)",
  "Pakil (Laguna)",
  "Pangil (Laguna)",
  "Pila (Laguna)",
  "Rizal (Laguna)",
  "San Pablo City (Laguna)",
  "San Pedro (Laguna)",
  "Santa Cruz (Laguna)",
  "Santa Maria (Laguna)",
  "Santa Rosa City (Laguna)",
  "Siniloan (Laguna)",
  "Victoria (Laguna)",
  "Boac (Marinduque)",
  "Buenavista (Marinduque)",
  "Gasan (Marinduque)",
  "Mogpog (Marinduque)",
  "Santa Cruz (Marinduque)",
  "Torrijos (Marinduque)",
  "Aroroy (Masbate)",
  "Baleno (Masbate)",
  "Balud (Masbate)",
  "Batuan (Masbate)",
  "Cataingan (Masbate)",
  "Cawayan (Masbate)",
  "Claveria (Masbate)",
  "Dimasalang (Masbate)",
  "Esperanza (Masbate)",
  "Mandaon (Masbate)",
  "Masbate City (Masbate)",
  "Milagros (Masbate)",
  "Mobo (Masbate)",
  "Monreal (Masbate)",
  "Palanas (Masbate)",
  "Pio V. Corpuz (Masbate)",
  "Placer (Masbate)",
  "San Fernando (Masbate) - 산페르난도",
  "San Jacinto (Masbate)",
  "San Pascual (Masbate)",
  "Uson (Masbate)",
  "Kalookan City (Metropolitan Manila) - 칼로오칸",
  "Las Pinas (Metropolitan Manila) - 라스피나스",
  "Makati City (Metropolitan Manila) - 마카티",
  "Malabon (Metropolitan Manila) - 말라본",
  "Mandaluyong (Metropolitan Manila) - 만달루용",
  "Manila (Metropolitan Manila) - 마닐라",
  "Marikina (Metropolitan Manila) - 마리키나",
  "Muntinlupa (Metropolitan Manila) - 문틴루파",
  "Paranaque (Metropolitan Manila) - 파라냐케",
  "Pasay City (Metropolitan Manila) - 파사이",
  "Pasig City (Metropolitan Manila) - 파식",
  "Quezon City (Metropolitan Manila) - 퀘존",
  "San Juan City (Metropolitan Manila) - 산후안",
  "Taguig (Metropolitan Manila) - 따귁",
  "Valenzuela (Metropolitan Manila) - 발렌수엘라",
  "Barlig (Mountain Province)",
  "Bauko (Mountain Province)",
  "Besao (Mountain Province)",
  "Bontoc (Mountain Province)",
  "Natonin (Mountain Province)",
  "Paracelis (Mountain Province)",
  "Sabangan (Mountain Province)",
  "Sadanga (Mountain Province)",
  "Sagada (Mountain Province)",
  "Tadian (Mountain Province)",
  "Aliaga (Nueva Ecija)",
  "Bongabon (Nueva Ecija)",
  "Cabanatuan City (Nueva Ecija)",
  "Cabiao (Nueva Ecija)",
  "Carranglan (Nueva Ecija)",
  "Cuyapo (Nueva Ecija)",
  "Gabaldon (Nueva Ecija)",
  "Gapan City (Nueva Ecija)",
  "General Mamerto Natividad (Nueva Ecija)",
  "General Tinio (Nueva Ecija)",
  "Guimba (Nueva Ecija)",
  "Jaen (Nueva Ecija)",
  "Laur (Nueva Ecija)",
  "Licab (Nueva Ecija)",
  "Llanera (Nueva Ecija)",
  "Lupao (Nueva Ecija)",
  "Mu├â┬▒oz City (Nueva Ecija)",
  "Nampicuan (Nueva Ecija)",
  "Palayan City (Nueva Ecija)",
  "Pantabangan (Nueva Ecija)",
  "Pe├â┬▒aranda (Nueva Ecija)",
  "Quezon (Nueva Ecija)",
  "Rizal (Nueva Ecija)",
  "San Antonio (Nueva Ecija)",
  "San Isidro (Nueva Ecija)",
  "San Jose City (Nueva Ecija)",
  "San Leonardo (Nueva Ecija)",
  "Santa Rosa (Nueva Ecija)",
  "Santo Domingo (Nueva Ecija)",
  "Talavera (Nueva Ecija)",
  "Talugtug (Nueva Ecija)",
  "Zaragoza (Nueva Ecija)",
  "Alfonso Castaneda (Nueva Vizcaya)",
  "Ambaguio (Nueva Vizcaya)",
  "Aritao (Nueva Vizcaya)",
  "Bagabag (Nueva Vizcaya)",
  "Bambang (Nueva Vizcaya)",
  "Bayombong (Nueva Vizcaya)",
  "Diadi (Nueva Vizcaya)",
  "Dupax Del Norte (Nueva Vizcaya)",
  "Dupax Del Sur (Nueva Vizcaya)",
  "Kasibu (Nueva Vizcaya)",
  "Kayapa (Nueva Vizcaya)",
  "Quezon (Nueva Vizcaya)",
  "Santa Fe (Nueva Vizcaya)",
  "Solano (Nueva Vizcaya)",
  "Villaverde (Nueva Vizcaya)",
  "Abra de Ilog (Occidental Mindoro)",
  "Calintaan (Occidental Mindoro)",
  "Looc (Occidental Mindoro)",
  "Lubang (Occidental Mindoro)",
  "Magsaysay (Occidental Mindoro)",
  "Mamburao (Occidental Mindoro)",
  "Paluan (Occidental Mindoro)",
  "Rizal (Occidental Mindoro)",
  "Sablayan (Occidental Mindoro)",
  "San Jose (Occidental Mindoro)",
  "Santa Cruz (Occidental Mindoro)",
  "Baco (Oriental Mindoro)",
  "Bansud (Oriental Mindoro)",
  "Bongabong (Oriental Mindoro)",
  "Bulalacao (Oriental Mindoro)",
  "Calapan City (Oriental Mindoro)",
  "Gloria (Oriental Mindoro)",
  "Mansalay (Oriental Mindoro)",
  "Naujan (Oriental Mindoro)",
  "Pinamalayan (Oriental Mindoro)",
  "Pola (Oriental Mindoro)",
  "Puerto Galera (Oriental Mindoro)",
  "Roxas (Oriental Mindoro)",
  "San Teodoro (Oriental Mindoro)",
  "Socorro (Oriental Mindoro)",
  "Victoria (Oriental Mindoro)",
  "Aborlan (Palawan)",
  "Agutaya (Palawan)",
  "Araceli (Palawan)",
  "Balabac (Palawan)",
  "Bataraza (Palawan)",
  "Brooke's Point (Palawan)",
  "Busuanga (Palawan)",
  "Cagayancillo (Palawan)",
  "Coron (Palawan)",
  "Culion (Palawan)",
  "Cuyo (Palawan)",
  "Dumaran (Palawan)",
  "El Nido (Palawan)",
  "Linapacan (Palawan)",
  "Magsaysay (Palawan)",
  "Narra (Palawan)",
  "Puerto Princesa City (Palawan)",
  "Quezon (Palawan)",
  "Rizal (Palawan) - 리잘",
  "Roxas (Palawan)",
  "San Vicente (Palawan)",
  "Sofronio Espanola (Palawan)",
  "Taytay (Palawan) - 타이타이",
  "Angeles City (Pampanga) - 앙헬레스",
  "Apalit (Pampanga)",
  "Arayat (Pampanga)",
  "Bacolor (Pampanga)",
  "Candaba (Pampanga)",
  "Floridablanca (Pampanga)",
  "Guagua (Pampanga)",
  "Lubao (Pampanga)",
  "Mabalacat (Pampanga) - 마발라캇",
  "Macabebe (Pampanga)",
  "Magalang (Pampanga) - 마갈랑",
  "Masantol (Pampanga)",
  "Mexico (Pampanga) - 멕시코",
  "Minalin (Pampanga)",
  "Porac (Pampanga) - 포락",
  "San Fernando City (Pampanga) - 산페르난도",
  "San Luis (Pampanga)",
  "San Simon (Pampanga)",
  "Santa Ana (Pampanga)",
  "Santa Rita (Pampanga)",
  "Santo Tomas (Pampanga)",
  "Sasmuan (Pampanga)",
  "Agno (Pangasinan)",
  "Aguilar (Pangasinan)",
  "Alaminos City (Pangasinan)",
  "Alcala (Pangasinan)",
  "Anda (Pangasinan)",
  "Asingan (Pangasinan)",
  "Balungao (Pangasinan)",
  "Bani (Pangasinan)",
  "Basista (Pangasinan)",
  "Bautista (Pangasinan)",
  "Bayambang (Pangasinan)",
  "Binalonan (Pangasinan)",
  "Binmaley (Pangasinan)",
  "Bolinao (Pangasinan)",
  "Bugallon (Pangasinan)",
  "Burgos (Pangasinan)",
  "Calasiao (Pangasinan)",
  "Dagupan City (Pangasinan)",
  "Dasol (Pangasinan)",
  "Infanta (Pangasinan)",
  "Labrador (Pangasinan)",
  "Laoac (Pangasinan)",
  "Lingayen (Pangasinan)",
  "Mabini (Pangasinan)",
  "Malasiqui (Pangasinan)",
  "Manaoag (Pangasinan)",
  "Mangaldan (Pangasinan)",
  "Mangatarem (Pangasinan)",
  "Mapandan (Pangasinan)",
  "Natividad (Pangasinan)",
  "Pozzorubio (Pangasinan)",
  "Rosales (Pangasinan)",
  "San Carlos City (Pangasinan)",
  "San Fabian (Pangasinan)",
  "San Jacinto (Pangasinan)",
  "San Manuel (Pangasinan)",
  "San Nicolas (Pangasinan)",
  "San Quintin (Pangasinan)",
  "Santa Barbara (Pangasinan)",
  "Santa Maria (Pangasinan)",
  "Santo Tomas (Pangasinan)",
  "Sison (Pangasinan)",
  "Sual (Pangasinan)",
  "Tayug (Pangasinan)",
  "Umingan (Pangasinan)",
  "Urbiztondo (Pangasinan)",
  "Urdaneta City (Pangasinan)",
  "Villasis (Pangasinan)",
  "Agdangan (Quezon)",
  "Alabat (Quezon)",
  "Atimonan (Quezon)",
  "Buenavista (Quezon)",
  "Burdeos (Quezon)",
  "Calauag (Quezon)",
  "Candelaria (Quezon)",
  "Catanauan (Quezon)",
  "Dolores (Quezon)",
  "General Luna (Quezon)",
  "General Nakar (Quezon)",
  "Guinayangan (Quezon)",
  "Gumaca (Quezon)",
  "Infanta (Quezon)",
  "Jomalig (Quezon)",
  "Lopez (Quezon)",
  "Lucban (Quezon)",
  "Lucena City (Quezon)",
  "Macalelon (Quezon)",
  "Mauban (Quezon)",
  "Mulanay (Quezon)",
  "Padre Burgos (Quezon)",
  "Pagbilao (Quezon)",
  "Panukulan (Quezon)",
  "Patnanungan (Quezon)",
  "Perez (Quezon)",
  "Pitogo (Quezon)",
  "Plaridel (Quezon)",
  "Polillo (Quezon)",
  "Quezon (Quezon)",
  "Real (Quezon)",
  "Sampaloc (Quezon)",
  "San Andres (Quezon)",
  "San Antonio (Quezon)",
  "San Francisco (Quezon)",
  "San Narciso (Quezon)",
  "Sariaya (Quezon)",
  "Tagkawayan (Quezon)",
  "Tayabas City (Quezon)",
  "Tiaong (Quezon)",
  "Unisan (Quezon)",
  "Aglipay (Quirino)",
  "Cabarroguis (Quirino)",
  "Diffun (Quirino)",
  "Maddela (Quirino)",
  "Nagtipunan (Quirino)",
  "Saguday (Quirino)",
  "Angono (Rizal)",
  "Antipolo City (Rizal) - 안티폴로",
  "Baras (Rizal)",
  "Binangonan (Rizal)",
  "Cainta (Rizal)",
  "Cardona (Rizal)",
  "Jala-Jala (Rizal)",
  "Morong (Rizal)",
  "Pililla (Rizal)",
  "Rodriguez (Rizal)",
  "San Mateo (Rizal)",
  "Tanay (Rizal)",
  "Taytay (Rizal) - 타이타이",
  "Teresa (Rizal)",
  "Alcantara (Romblon)",
  "Banton (Romblon)",
  "Cajidiocan (Romblon)",
  "Calatrava (Romblon)",
  "Concepcion (Romblon)",
  "Corcuera (Romblon)",
  "Ferrol (Romblon)",
  "Looc (Romblon)",
  "Magdiwang (Romblon)",
  "Odiongan (Romblon)",
  "Romblon (Romblon)",
  "San Agustin (Romblon)",
  "San Andres (Romblon)",
  "San Fernando (Romblon)",
  "San Jose (Romblon)",
  "Santa Fe (Romblon)",
  "Santa Maria (Romblon)",
  "Barcelona (Sorsogon)",
  "Bulan (Sorsogon)",
  "Bulusan (Sorsogon)",
  "Casiguran (Sorsogon)",
  "Castilla (Sorsogon)",
  "Donsol (Sorsogon)",
  "Gubat (Sorsogon)",
  "Irosin (Sorsogon)",
  "Juban (Sorsogon)",
  "Magallanes (Sorsogon)",
  "Matnog (Sorsogon)",
  "Pilar (Sorsogon)",
  "Prieto Diaz (Sorsogon)",
  "Santa Magdalena (Sorsogon)",
  "Sorsogon City (Sorsogon)",
  "Anao (Tarlac)",
  "Bamban (Tarlac)",
  "Camiling (Tarlac)",
  "Capas (Tarlac)",
  "Concepcion (Tarlac)",
  "Gerona (Tarlac)",
  "La Paz (Tarlac)",
  "Mayantoc (Tarlac)",
  "Moncada (Tarlac)",
  "Paniqui (Tarlac)",
  "Pura (Tarlac)",
  "Ramos (Tarlac)",
  "San Clemente (Tarlac)",
  "San Jose (Tarlac)",
  "San Manuel (Tarlac)",
  "Santa Ignacia (Tarlac)",
  "Tarlac City (Tarlac)",
  "Victoria (Tarlac)",
  "Botolan (Zambales)",
  "Cabangan (Zambales)",
  "Candelaria (Zambales)",
  "Castillejos (Zambales)",
  "Iba (Zambales)",
  "Masinloc (Zambales)",
  "Olongapo City (Zambales)",
  "Palauig (Zambales)",
  "San Antonio (Zambales)",
  "San Felipe (Zambales)",
  "San Marcelino (Zambales)",
  "San Narciso (Zambales)",
  "Santa Cruz (Zambales)",
  "Subic (Zambales) - 수빅",
  "Altavas (Aklan)",
  "Balete (Aklan)",
  "Banga (Aklan)",
  "Batan (Aklan) - 바탄",
  "Buruanga (Aklan)",
  "Ibajay (Aklan)",
  "Kalibo (Aklan)",
  "Lezo (Aklan)",
  "Libacao (Aklan)",
  "Madalag (Aklan)",
  "Makato (Aklan)",
  "Malay (Aklan)",
  "Malinao (Aklan)",
  "Nabas (Aklan)",
  "New Washington (Aklan)",
  "Numancia (Aklan)",
  "Tangalan (Aklan)",
  "Anini-Y (Antique)",
  "Barbaza (Antique)",
  "Belison (Antique)",
  "Bugasong (Antique)",
  "Caluya (Antique)",
  "Culasi (Antique)",
  "Hamtic (Antique)",
  "Laua-An (Antique)",
  "Libertad (Antique)",
  "Pandan (Antique)",
  "Patnongon (Antique)",
  "San Jose (Antique)",
  "San Remigio (Antique)",
  "Sebaste (Antique)",
  "Sibalom (Antique)",
  "Tibiao (Antique)",
  "Tobias Fornier (Antique)",
  "Valderrama (Antique)",
  "Almeria (Biliran)",
  "Biliran (Biliran)",
  "Cabucgayan (Biliran)",
  "Caibiran (Biliran)",
  "Culaba (Biliran)",
  "Kawayan (Biliran)",
  "Maripipi (Biliran)",
  "Naval (Biliran)",
  "Albuquerque (Bohol)",
  "Alicia (Bohol)",
  "Anda (Bohol)",
  "Antequera (Bohol)",
  "Baclayon (Bohol)",
  "Balilihan (Bohol)",
  "Batuan (Bohol) - 바투안",
  "Bien Unido (Bohol)",
  "Bilar (Bohol)",
  "Buenavista (Bohol)",
  "Calape (Bohol)",
  "Candijay (Bohol)",
  "Carmen (Bohol)",
  "Catigbian (Bohol)",
  "Clarin (Bohol)",
  "Corella (Bohol)",
  "Cortes (Bohol)",
  "Dagohoy (Bohol)",
  "Danao (Bohol)",
  "Dauis (Bohol)",
  "Dimiao (Bohol)",
  "Duero (Bohol)",
  "Garcia Hernandez (Bohol)",
  "Guindulman (Bohol)",
  "Inabanga (Bohol)",
  "Jagna (Bohol)",
  "Jetafe (Bohol)",
  "Lila (Bohol)",
  "Loay (Bohol)",
  "Loboc (Bohol) - 로복",
  "Loon (Bohol)",
  "Mabini (Bohol)",
  "Maribojoc (Bohol)",
  "Panglao (Bohol)",
  "Pilar (Bohol)",
  "Pres. Carlos P. Garcia (Bohol)",
  "Sagbayan (Bohol)",
  "San Isidro (Bohol)",
  "San Miguel (Bohol)",
  "Sevilla (Bohol)",
  "Sierra Bullones (Bohol)",
  "Sikatuna (Bohol)",
  "Tagbilaran City (Bohol) - 타그빌라란",
  "Talibon (Bohol)",
  "Trinidad (Bohol)",
  "Tubigon (Bohol)",
  "Ubay (Bohol)",
  "Valencia (Bohol) - 발렌시아",
  "Cuartero (Capiz)",
  "Dao (Capiz)",
  "Dumalag (Capiz)",
  "Dumarao (Capiz)",
  "Ivisan (Capiz)",
  "Jamindan (Capiz)",
  "Ma-Ayon (Capiz)",
  "Mambusao (Capiz)",
  "Panay (Capiz)",
  "Panitan (Capiz)",
  "Pilar (Capiz)",
  "Pontevedra (Capiz)",
  "President Roxas (Capiz)",
  "Roxas City (Capiz)",
  "Sapi-An (Capiz)",
  "Sigma (Capiz)",
  "Tapaz (Capiz)",
  "Alcantara (Cebu)",
  "Alcoy (Cebu)",
  "Alegria (Cebu)",
  "Aloguinsan (Cebu)",
  "Argao (Cebu)",
  "Asturias (Cebu)",
  "Badian (Cebu)",
  "Balamban (Cebu)",
  "Bantayan (Cebu)",
  "Barili (Cebu)",
  "Bogo City (Cebu)",
  "Boljoon (Cebu)",
  "Borbon (Cebu)",
  "Carcar (Cebu)",
  "Carmen (Cebu)",
  "Catmon (Cebu)",
  "Cebu City (Cebu) - 세부",
  "Compostela (Cebu)",
  "Consolacion (Cebu)",
  "Cordoba (Cebu)",
  "Daanbantayan (Cebu)",
  "Dalaguete (Cebu)",
  "Danao City (Cebu)",
  "Dumanjug (Cebu)",
  "Ginatilan (Cebu)",
  "Lapu-Lapu City (Cebu) - 라푸라푸",
  "Liloan (Cebu)",
  "Madridejos (Cebu)",
  "Malabuyoc (Cebu)",
  "Mandaue City (Cebu) - 만다웨",
  "Medellin (Cebu)",
  "Minglanilla (Cebu)",
  "Moalboal (Cebu)",
  "Naga City (Cebu) - 나가",
  "Oslob (Cebu) - 오슬롭",
  "Pilar (Cebu)",
  "Pinamungahan (Cebu)",
  "Poro (Cebu)",
  "Ronda (Cebu)",
  "Samboan (Cebu)",
  "San Fernando (Cebu)",
  "San Francisco (Cebu)",
  "San Remigio (Cebu)",
  "Santa Fe (Cebu)",
  "Santander (Cebu)",
  "Sibonga (Cebu)",
  "Sogod (Cebu)",
  "Tabogon (Cebu)",
  "Tabuelan (Cebu)",
  "Talisay City (Cebu)",
  "Toledo City (Cebu)",
  "Tuburan (Cebu)",
  "Tudela (Cebu)",
  "Arteche (Eastern Samar)",
  "Balangiga (Eastern Samar)",
  "Balangkayan (Eastern Samar)",
  "Borongan City (Eastern Samar)",
  "Can-Avid (Eastern Samar)",
  "Dolores (Eastern Samar)",
  "General Macarthur (Eastern Samar)",
  "Giporlos (Eastern Samar)",
  "Guiuan (Eastern Samar)",
  "Hernani (Eastern Samar)",
  "Jipapad (Eastern Samar)",
  "Lawaan (Eastern Samar)",
  "Llorente (Eastern Samar)",
  "Maslog (Eastern Samar)",
  "Maydolong (Eastern Samar)",
  "Mercedes (Eastern Samar)",
  "Oras (Eastern Samar)",
  "Quinapondan (Eastern Samar)",
  "Salcedo (Eastern Samar)",
  "San Julian (Eastern Samar)",
  "San Policarpo (Eastern Samar)",
  "Sulat (Eastern Samar)",
  "Taft (Eastern Samar)",
  "Buenavista (Guimaras)",
  "Jordan (Guimaras)",
  "Nueva Valencia (Guimaras)",
  "San Lorenzo (Guimaras)",
  "Sibunag (Guimaras)",
  "Ajuy (Iloilo)",
  "Alimodian (Iloilo)",
  "Anilao (Iloilo)",
  "Badiangan (Iloilo)",
  "Balasan (Iloilo)",
  "Banate (Iloilo)",
  "Barotac Nuevo (Iloilo)",
  "Barotac Viejo (Iloilo)",
  "Batad (Iloilo)",
  "Bingawan (Iloilo)",
  "Cabatuan (Iloilo)",
  "Calinog (Iloilo)",
  "Carles (Iloilo)",
  "Concepcion (Iloilo)",
  "Dingle (Iloilo)",
  "Duenas (Iloilo)",
  "Dumangas (Iloilo)",
  "Estancia (Iloilo)",
  "Guimbal (Iloilo)",
  "Igbaras (Iloilo)",
  "Iloilo City (Iloilo) - 일로일로",
  "Janiuay (Iloilo)",
  "Lambunao (Iloilo)",
  "Leganes (Iloilo)",
  "Lemery (Iloilo)",
  "Leon (Iloilo)",
  "Maasin (Iloilo)",
  "Miagao (Iloilo)",
  "Mina (Iloilo)",
  "New Lucena (Iloilo)",
  "Oton (Iloilo)",
  "Passi City (Iloilo)",
  "Pavia (Iloilo)",
  "Pototan (Iloilo)",
  "San Dionisio (Iloilo)",
  "San Enrique (Iloilo)",
  "San Joaquin (Iloilo)",
  "San Miguel (Iloilo)",
  "San Rafael (Iloilo)",
  "Santa Barbara (Iloilo)",
  "Sara (Iloilo)",
  "Tigbauan (Iloilo)",
  "Tubungan (Iloilo)",
  "Zarraga (Iloilo)",
  "Abuyog (Leyte)",
  "Alangalang (Leyte)",
  "Albuera (Leyte)",
  "Babatngon (Leyte)",
  "Barugo (Leyte)",
  "Bato (Leyte)",
  "Baybay City (Leyte)",
  "Burauen (Leyte)",
  "Calubian (Leyte)",
  "Capoocan (Leyte) - 카푸칸",
  "Carigara (Leyte)",
  "Dagami (Leyte)",
  "Dulag (Leyte)",
  "Hilongos (Leyte)",
  "Hindang (Leyte)",
  "Inopacan (Leyte)",
  "Isabel (Leyte)",
  "Jaro (Leyte)",
  "Javier (Leyte)",
  "Julita (Leyte)",
  "Kananga (Leyte)",
  "La Paz (Leyte)",
  "Leyte (Leyte) - 레이테",
  "Macarthur (Leyte)",
  "Mahaplag (Leyte)",
  "Matag-Ob (Leyte)",
  "Matalom (Leyte)",
  "Mayorga (Leyte)",
  "Merida (Leyte)",
  "Ormoc City (Leyte) - 올목",
  "Palo (Leyte)",
  "Palompon (Leyte)",
  "Pastrana (Leyte)",
  "San Isidro (Leyte)",
  "San Miguel (Leyte)",
  "Santa Fe (Leyte)",
  "Tabango (Leyte)",
  "Tabontabon (Leyte)",
  "Tacloban City (Leyte)",
  "Tanauan (Leyte)",
  "Tolosa (Leyte)",
  "Tunga (Leyte)",
  "Villaba (Leyte)",
  "Bacolod City (Negros Occidental) - 바콜로드",
  "Bago City (Negros Occidental)",
  "Binalbagan (Negros Occidental)",
  "Cadiz City (Negros Occidental)",
  "Calatrava (Negros Occidental)",
  "Candoni (Negros Occidental)",
  "Cauayan (Negros Occidental)",
  "Enrique B. Magalona (Negros Occidental)",
  "Escalante City (Negros Occidental)",
  "Himamaylan City (Negros Occidental)",
  "Hinigaran (Negros Occidental)",
  "Hinoba-An (Negros Occidental)",
  "Ilog (Negros Occidental)",
  "Isabela (Negros Occidental)",
  "Kabankalan City (Negros Occidental)",
  "La Carlota City (Negros Occidental)",
  "La Castellana (Negros Occidental)",
  "Manapla (Negros Occidental)",
  "Moises Padilla (Negros Occidental)",
  "Murcia (Negros Occidental)",
  "Pontevedra (Negros Occidental)",
  "Pulupandan (Negros Occidental)",
  "Sagay City (Negros Occidental)",
  "Salvador Benedicto (Negros Occidental)",
  "San Carlos City (Negros Occidental)",
  "San Enrique (Negros Occidental)",
  "Silay City (Negros Occidental)",
  "Sipalay City (Negros Occidental)",
  "Talisay City (Negros Occidental)",
  "Toboso (Negros Occidental)",
  "Valladolid (Negros Occidental)",
  "Victorias City (Negros Occidental)",
  "Amlan (Negros Oriental)",
  "Ayungon (Negros Oriental)",
  "Bacong (Negros Oriental)",
  "Bais City (Negros Oriental)",
  "Basay (Negros Oriental)",
  "Bayawan City (Negros Oriental)",
  "Bindoy (Negros Oriental)",
  "Canlaon City (Negros Oriental)",
  "Dauin (Negros Oriental)",
  "Dumaguete City (Negros Oriental) - 두마게티",
  "Guihulngan City (Negros Oriental)",
  "Jimalalud (Negros Oriental)",
  "La Libertad (Negros Oriental)",
  "Mabinay (Negros Oriental)",
  "Manjuyod (Negros Oriental)",
  "Pamplona (Negros Oriental)",
  "San Jose (Negros Oriental)",
  "Santa Catalina (Negros Oriental)",
  "Siaton (Negros Oriental)",
  "Sibulan (Negros Oriental)",
  "Tanjay City (Negros Oriental)",
  "Tayasan (Negros Oriental)",
  "Valencia (Negros Oriental)",
  "Vallehermoso (Negros Oriental)",
  "Zamboanguita (Negros Oriental)",
  "Allen (Northern Samar)",
  "Biri (Northern Samar)",
  "Bobon (Northern Samar)",
  "Capul (Northern Samar)",
  "Catarman (Northern Samar)",
  "Catubig (Northern Samar)",
  "Gamay (Northern Samar)",
  "Laoang (Northern Samar)",
  "Lapinig (Northern Samar)",
  "Las Navas (Northern Samar)",
  "Lavezares (Northern Samar)",
  "Lope de Vega (Northern Samar)",
  "Mapanas (Northern Samar)",
  "Mondragon (Northern Samar)",
  "Palapag (Northern Samar)",
  "Pambujan (Northern Samar)",
  "Rosario (Northern Samar)",
  "San Antonio (Northern Samar)",
  "San Isidro (Northern Samar)",
  "San Jose (Northern Samar)",
  "San Roque (Northern Samar)",
  "San Vicente (Northern Samar)",
  "Silvino Lobos (Northern Samar)",
  "Victoria (Northern Samar)",
  "Almagro (Samar)",
  "Basey (Samar)",
  "Calbayog City (Samar)",
  "Calbiga (Samar)",
  "Catbalogan City (Samar)",
  "Daram (Samar)",
  "Gandara (Samar)",
  "Hinabangan (Samar)",
  "Jiabong (Samar)",
  "Marabut (Samar)",
  "Matuguinao (Samar)",
  "Motiong (Samar)",
  "Pagsanghan (Samar)",
  "Paranas (Samar)",
  "Pinabacdao (Samar)",
  "San Jorge (Samar)",
  "San Jose de Buan (Samar)",
  "San Sebastian (Samar)",
  "Santa Margarita (Samar)",
  "Santa Rita (Samar)",
  "Santo Nino (Samar)",
  "Tagapul-An (Samar)",
  "Talalora (Samar)",
  "Tarangnan (Samar)",
  "Villareal (Samar)",
  "Zumarraga (Samar)",
  "Enrique Villanueva (Siquijor)",
  "Larena (Siquijor)",
  "Lazi (Siquijor)",
  "Maria (Siquijor)",
  "San Juan (Siquijor)",
  "Siquijor (Siquijor)",
  "Anahawan (Southern Leyte)",
  "Bontoc (Southern Leyte)",
  "Hinunangan (Southern Leyte)",
  "Hinundayan (Southern Leyte)",
  "Libagon (Southern Leyte)",
  "Liloan (Southern Leyte)",
  "Limasawa (Southern Leyte)",
  "Maasin City (Southern Leyte)",
  "Macrohon (Southern Leyte)",
  "Malitbog (Southern Leyte)",
  "Padre Burgos (Southern Leyte)",
  "Pintuyan (Southern Leyte)",
  "Saint Bernard (Southern Leyte)",
  "San Francisco (Southern Leyte)",
  "San Juan (Southern Leyte)",
  "San Ricardo (Southern Leyte)",
  "Silago (Southern Leyte)",
  "Sogod (Southern Leyte)",
  "Tomas Oppus (Southern Leyte)",
  "Buenavista (Agusan del Norte)",
  "Butuan City (Agusan del Norte)",
  "Cabadbaran City (Agusan del Norte)",
  "Carmen (Agusan del Norte)",
  "Jabonga (Agusan del Norte)",
  "Kitcharao (Agusan del Norte)",
  "Las Nieves (Agusan del Norte)",
  "Magallanes (Agusan del Norte)",
  "Nasipit (Agusan del Norte)",
  "Remedios T. Romualdez (Agusan del Norte)",
  "Santiago (Agusan del Norte)",
  "Tubay (Agusan del Norte)",
  "Bayugan City (Agusan del Sur)",
  "Bunawan (Agusan del Sur)",
  "Esperanza (Agusan del Sur)",
  "La Paz (Agusan del Sur)",
  "Loreto (Agusan del Sur)",
  "Prosperidad (Agusan del Sur)",
  "Rosario (Agusan del Sur)",
  "San Francisco (Agusan del Sur)",
  "San Luis (Agusan del Sur)",
  "Santa Josefa (Agusan del Sur)",
  "Sibagat (Agusan del Sur)",
  "Talacogon (Agusan del Sur)",
  "Trento (Agusan del Sur)",
  "Veruela (Agusan del Sur)",
  "Akbar (Basilan)",
  "Al-Barka (Basilan)",
  "Hadji Mohammad Ajul (Basilan)",
  "Isabela City (Basilan)",
  "Lamitan City (Basilan)",
  "Lantawan (Basilan)",
  "Maluso (Basilan)",
  "Sumisip (Basilan)",
  "Tipo-Tipo (Basilan)",
  "Tuburan (Basilan)",
  "Ungkaya Pukan (Basilan)",
  "Baungon (Bukidnon)",
  "Cabanglasan (Bukidnon)",
  "Damulog (Bukidnon)",
  "Dangcagan (Bukidnon)",
  "Don Carlos (Bukidnon)",
  "Impasug-Ong (Bukidnon)",
  "Kadingilan (Bukidnon)",
  "Kalilangan (Bukidnon)",
  "Kibawe (Bukidnon)",
  "Kitaotao (Bukidnon)",
  "Lantapan (Bukidnon)",
  "Libona (Bukidnon)",
  "Malaybalay City (Bukidnon)",
  "Malitbog (Bukidnon)",
  "Manolo Fortich (Bukidnon)",
  "Maramag (Bukidnon)",
  "Pangantucan (Bukidnon)",
  "Quezon (Bukidnon)",
  "San Fernando (Bukidnon)",
  "Sumilao (Bukidnon)",
  "Talakag (Bukidnon)",
  "Valencia City (Bukidnon)",
  "Catarman (Camiguin)",
  "Guinsiliban (Camiguin)",
  "Mahinog (Camiguin)",
  "Mambajao (Camiguin)",
  "Sagay (Camiguin)",
  "Compostela (Compostela Valley)",
  "Laak (Compostela Valley)",
  "Mabini (Compostela Valley)",
  "Maco (Compostela Valley)",
  "Maragusan (Compostela Valley)",
  "Mawab (Compostela Valley)",
  "Monkayo (Compostela Valley)",
  "Montevista (Compostela Valley)",
  "Nabunturan (Compostela Valley)",
  "New Bataan (Compostela Valley)",
  "Pantukan (Compostela Valley)",
  "Asuncion (Davao del Norte)",
  "Braulio E. Dujali (Davao del Norte)",
  "Carmen (Davao del Norte)",
  "Kapalong (Davao del Norte)",
  "New Corella (Davao del Norte)",
  "Panabo City (Davao del Norte)",
  "Samal City (Davao del Norte)",
  "San Isidro (Davao del Norte)",
  "Santo Tomas (Davao del Norte)",
  "Tagum City (Davao del Norte)",
  "Talaingod (Davao del Norte)",
  "Bansalan (Davao del Sur)",
  "Davao City (Davao del Sur) - 다바오",
  "Digos City (Davao del Sur)",
  "Don Marcelino (Davao del Sur)",
  "Hagonoy (Davao del Sur)",
  "Jose Abad Santos (Davao del Sur)",
  "Kiblawan (Davao del Sur)",
  "Magsaysay (Davao del Sur)",
  "Malalag (Davao del Sur)",
  "Malita (Davao del Sur)",
  "Matanao (Davao del Sur)",
  "Padada (Davao del Sur)",
  "Santa Cruz (Davao del Sur)",
  "Santa Maria (Davao del Sur)",
  "Sarangani (Davao del Sur)",
  "Sulop (Davao del Sur)",
  "Baganga (Davao Oriental)",
  "Banaybanay (Davao Oriental)",
  "Boston (Davao Oriental)",
  "Caraga (Davao Oriental)",
  "Cateel (Davao Oriental)",
  "Governor Generoso (Davao Oriental)",
  "Lupon (Davao Oriental)",
  "Manay (Davao Oriental)",
  "Mati City (Davao Oriental)",
  "San Isidro (Davao Oriental)",
  "Tarragona (Davao Oriental)",
  "Basilisa (Dinagat Islands)",
  "Cagdianao (Dinagat Islands)",
  "Dinagat (Dinagat Islands)",
  "Libjo (Dinagat Islands)",
  "Loreto (Dinagat Islands)",
  "San Jose (Dinagat Islands)",
  "Tubajon (Dinagat Islands)",
  "Bacolod (Lanao del Norte)",
  "Baloi (Lanao del Norte)",
  "Baroy (Lanao del Norte)",
  "Iligan City (Lanao del Norte)",
  "Kapatagan (Lanao del Norte)",
  "Kauswagan (Lanao del Norte)",
  "Kolambugan (Lanao del Norte)",
  "Lala (Lanao del Norte)",
  "Linamon (Lanao del Norte)",
  "Magsaysay (Lanao del Norte)",
  "Maigo (Lanao del Norte)",
  "Matungao (Lanao del Norte)",
  "Munai (Lanao del Norte)",
  "Nunungan (Lanao del Norte)",
  "Pantao Ragat (Lanao del Norte)",
  "Pantar (Lanao del Norte)",
  "Poona Piagapo (Lanao del Norte)",
  "Salvador (Lanao del Norte)",
  "Sapad (Lanao del Norte)",
  "Sultan Naga Dimaporo (Lanao del Norte)",
  "Tagoloan (Lanao del Norte)",
  "Tangcal (Lanao del Norte)",
  "Tubod (Lanao del Norte)",
  "Bacolod Kalawi (Lanao del Sur)",
  "Balabagan (Lanao del Sur)",
  "Balindong (Lanao del Sur)",
  "Bayang (Lanao del Sur)",
  "Binidayan (Lanao del Sur)",
  "Buadiposo-Buntong (Lanao del Sur)",
  "Bubong (Lanao del Sur)",
  "Bumbaran (Lanao del Sur)",
  "Butig (Lanao del Sur)",
  "Calanogas (Lanao del Sur)",
  "Ditsaan-Ramain (Lanao del Sur)",
  "Ganassi (Lanao del Sur)",
  "Kapai (Lanao del Sur)",
  "Kapatagan (Lanao del Sur)",
  "Lumba-Bayabao (Lanao del Sur)",
  "Lumbaca Unayan (Lanao del Sur)",
  "Lumbatan (Lanao del Sur)",
  "Lumbayanague (Lanao del Sur)",
  "Madalum (Lanao del Sur)",
  "Madamba (Lanao del Sur)",
  "Maguing (Lanao del Sur)",
  "Malabang (Lanao del Sur)",
  "Marantao (Lanao del Sur)",
  "Marawi City (Lanao del Sur)",
  "Marogong (Lanao del Sur)",
  "Masiu (Lanao del Sur)",
  "Mulondo (Lanao del Sur)",
  "Pagayawan (Lanao del Sur)",
  "Piagapo (Lanao del Sur)",
  "Picong (Lanao del Sur)",
  "Poona Bayabao (Lanao del Sur)",
  "Pualas (Lanao del Sur)",
  "Saguiaran (Lanao del Sur)",
  "Sultan Dumalondong (Lanao del Sur)",
  "Tagoloan II (Lanao del Sur)",
  "Taraka (Lanao del Sur)",
  "Tubaran (Lanao del Sur)",
  "Tugaya (Lanao del Sur)",
  "Wao (Lanao del Sur)",
  "Ampatuan (Maguindanao)",
  "Buluan (Maguindanao)",
  "Cotabato City (Maguindanao)",
  "Datu Abdullah Sanki (Maguindanao)",
  "Datu Anggal Midtimbang (Maguindanao)",
  "Datu Paglas (Maguindanao)",
  "Datu Piang (Maguindanao)",
  "Datu Saudi-Ampatuan (Maguindanao)",
  "Datu Unsay (Maguindanao)",
  "Gen. S. K. Pendatun (Maguindanao)",
  "Guindulungan (Maguindanao)",
  "Mamasapano (Maguindanao)",
  "Mangudadatu (Maguindanao)",
  "Pagagawan (Maguindanao)",
  "Pagalungan (Maguindanao)",
  "Paglat (Maguindanao)",
  "Pandag (Maguindanao)",
  "Rajah Buayan (Maguindanao)",
  "Shariff Aguak (Maguindanao)",
  "South Upi (Maguindanao)",
  "Sultan Sa Barongis (Maguindanao)",
  "Talayan (Maguindanao)",
  "Talitay (Maguindanao)",
  "Aloran (Misamis Occidental)",
  "Baliangao (Misamis Occidental)",
  "Bonifacio (Misamis Occidental)",
  "Calamba (Misamis Occidental)",
  "Clarin (Misamis Occidental)",
  "Concepcion (Misamis Occidental)",
  "Don Victoriano Chiongbian (Misamis Occidental)",
  "Jimenez (Misamis Occidental)",
  "Lopez Jaena (Misamis Occidental)",
  "Oroquieta City (Misamis Occidental)",
  "Ozamis City (Misamis Occidental)",
  "Panaon (Misamis Occidental)",
  "Plaridel (Misamis Occidental)",
  "Sapang Dalaga (Misamis Occidental)",
  "Sinacaban (Misamis Occidental)",
  "Tangub City (Misamis Occidental)",
  "Tudela (Misamis Occidental)",
  "Alubijid (Misamis Oriental)",
  "Balingasag (Misamis Oriental)",
  "Balingoan (Misamis Oriental)",
  "Binuangan (Misamis Oriental)",
  "Cagayan de Oro City (Misamis Oriental) - 카가얀 데 오로",
  "Claveria (Misamis Oriental)",
  "El Salvador City (Misamis Oriental)",
  "Gingoog City (Misamis Oriental)",
  "Gitagum (Misamis Oriental)",
  "Initao (Misamis Oriental)",
  "Jasaan (Misamis Oriental)",
  "Kinoguitan (Misamis Oriental)",
  "Lagonglong (Misamis Oriental)",
  "Laguindingan (Misamis Oriental)",
  "Libertad (Misamis Oriental)",
  "Lugait (Misamis Oriental)",
  "Magsaysay (Misamis Oriental)",
  "Manticao (Misamis Oriental)",
  "Medina (Misamis Oriental)",
  "Naawan (Misamis Oriental)",
  "Opol (Misamis Oriental)",
  "Salay (Misamis Oriental)",
  "Sugbongcogon (Misamis Oriental)",
  "Tagoloan (Misamis Oriental)",
  "Talisayan (Misamis Oriental)",
  "Villanueva (Misamis Oriental)",
  "Alamada (North Cotabato)",
  "Aleosan (North Cotabato)",
  "Antipas (North Cotabato)",
  "Arakan (North Cotabato)",
  "Banisilan (North Cotabato)",
  "Carmen (North Cotabato)",
  "Kabacan (North Cotabato)",
  "Kidapawan City (North Cotabato)",
  "Libungan (North Cotabato)",
  "M'Lang (North Cotabato)",
  "Magpet (North Cotabato)",
  "Makilala (North Cotabato)",
  "Matalam (North Cotabato)",
  "Midsayap (North Cotabato)",
  "Pigkawayan (North Cotabato)",
  "Pikit (North Cotabato)",
  "President Roxas (North Cotabato)",
  "Tulunan (North Cotabato)",
  "Alabel (Sarangani)",
  "Glan (Sarangani)",
  "Kiamba (Sarangani)",
  "Maasim (Sarangani)",
  "Maitum (Sarangani)",
  "Malapatan (Sarangani)",
  "Malungon (Sarangani)",
  "Barira (Shariff Kabunsuan)",
  "Buldon (Shariff Kabunsuan)",
  "Datu Blah T. Sinsuat (Shariff Kabunsuan)",
  "Datu Odin Sinsuat (Shariff Kabunsuan)",
  "Kabuntalan (Shariff Kabunsuan)",
  "Matanog (Shariff Kabunsuan)",
  "Northern Kabuntalan (Shariff Kabunsuan)",
  "Parang (Shariff Kabunsuan)",
  "Sultan Kudarat (Shariff Kabunsuan)",
  "Sultan Mastura (Shariff Kabunsuan)",
  "Upi (Shariff Kabunsuan)",
  "Banga (South Cotabato)",
  "General Santos City (South Cotabato) - 제네럴 산토스",
  "Koronadal City (South Cotabato)",
  "Lake Sebu (South Cotabato)",
  "Norala (South Cotabato)",
  "Polomolok (South Cotabato)",
  "Santo Nino (South Cotabato)",
  "Surallah (South Cotabato)",
  "T'Boli (South Cotabato)",
  "Tampakan (South Cotabato)",
  "Tantangan (South Cotabato)",
  "Tupi (South Cotabato)",
  "Bagumbayan (Sultan Kudarat)",
  "Columbio (Sultan Kudarat)",
  "Esperanza (Sultan Kudarat)",
  "Isulan (Sultan Kudarat)",
  "Kalamansig (Sultan Kudarat)",
  "Lambayong (Sultan Kudarat)",
  "Lebak (Sultan Kudarat)",
  "Lutayan (Sultan Kudarat)",
  "Palimbang (Sultan Kudarat)",
  "President Quirino (Sultan Kudarat)",
  "Sen. Ninoy Aquino (Sultan Kudarat)",
  "Tacurong City (Sultan Kudarat)",
  "Hadji Panglima Tahil (Sulu)",
  "Indanan (Sulu)",
  "Kalingalan Caluang (Sulu)",
  "Lugus (Sulu)",
  "Luuk (Sulu)",
  "Maimbung (Sulu)",
  "Old Panamao (Sulu)",
  "Pandami (Sulu)",
  "Panglima Estino (Sulu)",
  "Pangutaran (Sulu)",
  "Parang (Sulu)",
  "Pata (Sulu)",
  "Patikul (Sulu)",
  "Siasi (Sulu)",
  "Talipao (Sulu)",
  "Tapul (Sulu)",
  "Tongkil (Sulu)",
  "Alegria (Surigao del Norte)",
  "Bacuag (Surigao del Norte)",
  "Burgos (Surigao del Norte)",
  "Claver (Surigao del Norte)",
  "Dapa (Surigao del Norte)",
  "Del Carmen (Surigao del Norte)",
  "General Luna (Surigao del Norte)",
  "Gigaquit (Surigao del Norte)",
  "Mainit (Surigao del Norte)",
  "Malimono (Surigao del Norte)",
  "Pilar (Surigao del Norte)",
  "Placer (Surigao del Norte)",
  "San Benito (Surigao del Norte)",
  "San Francisco (Surigao del Norte)",
  "San Isidro (Surigao del Norte)",
  "Santa Monica (Surigao del Norte)",
  "Sison (Surigao del Norte)",
  "Socorro (Surigao del Norte)",
  "Surigao City (Surigao del Norte)",
  "Tagana-An (Surigao del Norte)",
  "Tubod (Surigao del Norte)",
  "Barobo (Surigao del Sur)",
  "Bayabas (Surigao del Sur)",
  "Bislig City (Surigao del Sur)",
  "Cagwait (Surigao del Sur)",
  "Cantilan (Surigao del Sur)",
  "Carmen (Surigao del Sur)",
  "Carrascal (Surigao del Sur)",
  "Cortes (Surigao del Sur)",
  "Hinatuan (Surigao del Sur)",
  "Lanuza (Surigao del Sur)",
  "Lianga (Surigao del Sur)",
  "Lingig (Surigao del Sur)",
  "Madrid (Surigao del Sur)",
  "Marihatag (Surigao del Sur)",
  "San Agustin (Surigao del Sur)",
  "San Miguel (Surigao del Sur)",
  "Tagbina (Surigao del Sur)",
  "Tago (Surigao del Sur)",
  "Tandag City (Surigao del Sur)",
  "Bongao (Tawi-Tawi)",
  "Languyan (Tawi-Tawi)",
  "Mapun (Tawi-Tawi)",
  "Panglima Sugala (Tawi-Tawi)",
  "Sapa-Sapa (Tawi-Tawi)",
  "Sibutu (Tawi-Tawi)",
  "Simunul (Tawi-Tawi)",
  "Sitangkai (Tawi-Tawi)",
  "South Ubian (Tawi-Tawi)",
  "Tandubas (Tawi-Tawi)",
  "Turtle Islands (Tawi-Tawi)",
  "Bacungan (Zamboanga del Norte)",
  "Baliguian (Zamboanga del Norte)",
  "Dapitan City (Zamboanga del Norte)",
  "Dipolog City (Zamboanga del Norte)",
  "Godod (Zamboanga del Norte)",
  "Gutalac (Zamboanga del Norte)",
  "Jose Dalman (Zamboanga del Norte)",
  "Kalawit (Zamboanga del Norte)",
  "Katipunan (Zamboanga del Norte)",
  "La Libertad (Zamboanga del Norte)",
  "Labason (Zamboanga del Norte)",
  "Liloy (Zamboanga del Norte)",
  "Manukan (Zamboanga del Norte)",
  "Mutia (Zamboanga del Norte)",
  "Pinan (Zamboanga del Norte)",
  "Polanco (Zamboanga del Norte)",
  "Pres. Manuel A. Roxas (Zamboanga del Norte)",
  "Rizal (Zamboanga del Norte)",
  "Salug (Zamboanga del Norte)",
  "Sergio Osmena Sr. (Zamboanga del Norte)",
  "Siayan (Zamboanga del Norte)",
  "Sibuco (Zamboanga del Norte)",
  "Sibutad (Zamboanga del Norte)",
  "Sindangan (Zamboanga del Norte)",
  "Siocon (Zamboanga del Norte)",
  "Sirawai (Zamboanga del Norte)",
  "Tampilisan (Zamboanga del Norte)",
  "Aurora (Zamboanga del Sur)",
  "Bayog (Zamboanga del Sur)",
  "Dimataling (Zamboanga del Sur)",
  "Dinas (Zamboanga del Sur)",
  "Dumalinao (Zamboanga del Sur)",
  "Dumingag (Zamboanga del Sur)",
  "Guipos (Zamboanga del Sur)",
  "Josefina (Zamboanga del Sur)",
  "Kumalarang (Zamboanga del Sur)",
  "Labangan (Zamboanga del Sur)",
  "Lakewood (Zamboanga del Sur)",
  "Lapuyan (Zamboanga del Sur)",
  "Mahayag (Zamboanga del Sur)",
  "Margosatubig (Zamboanga del Sur)",
  "Midsalip (Zamboanga del Sur)",
  "Molave (Zamboanga del Sur)",
  "Pagadian City (Zamboanga del Sur)",
  "Pitogo (Zamboanga del Sur)",
  "Ramon Magsaysay (Zamboanga del Sur)",
  "San Miguel (Zamboanga del Sur)",
  "San Pablo (Zamboanga del Sur)",
  "Sominot (Zamboanga del Sur)",
  "Tabina (Zamboanga del Sur)",
  "Tambulig (Zamboanga del Sur)",
  "Tigbao (Zamboanga del Sur)",
  "Tukuran (Zamboanga del Sur)",
  "Vincenzo A. Sagun (Zamboanga del Sur)",
  "Zamboanga City (Zamboanga del Sur) - 잠보앙가",
  "Alicia (Zamboanga Sibugay)",
  "Buug (Zamboanga Sibugay)",
  "Diplahan (Zamboanga Sibugay)",
  "Imelda (Zamboanga Sibugay)",
  "Ipil (Zamboanga Sibugay)",
  "Kabasalan (Zamboanga Sibugay)",
  "Mabuhay (Zamboanga Sibugay)",
  "Malangas (Zamboanga Sibugay)",
  "Naga (Zamboanga Sibugay)",
  "Olutanga (Zamboanga Sibugay)",
  "Payao (Zamboanga Sibugay)",
  "Roseller Lim (Zamboanga Sibugay)",
  "Siay (Zamboanga Sibugay)",
  "Talusan (Zamboanga Sibugay)",
  "Titay (Zamboanga Sibugay)",
  "Tungawan (Zamboanga Sibugay)",
];
